# pinyin_map.py

import json
import os

# 声母映射
initials = {
    'b': '波',
    'p': '坡',
    'm': '么',
    'f': '佛',
    'd': '的',
    't': '特',
    'n': '呢',
    'l': '了',
    'g': '哥',
    'k': '科',
    'h': '喝',
    'j': '鸡',
    'q': '七',
    'x': '西',
    'zh': '知',
    'ch': '吃',
    'sh': '诗',
    'r': '日',
    'z': '资',
    'c': '刺',
    's': '思',
    'y': '衣',
    'w': '屋',
}

# 韵母映射（按拼音标准顺序排列）
finals = {
    # 单韵母
    'a': '啊',
    'o': '哦',
    'e': '饿',
    'i': '一',
    'u': '乌',
    'v': '愚',

    # 复韵母
    'ai': '挨',
    'ei': '诶',
    'ui': '威',
    'ao': '奥',
    'ou': '欧',
    'iu': '优',
    'ie': '也',
    've': '约',

    # 鼻韵母
    'an': '安',
    'en': '恩',
    'in': '因',
    'un': '温',
    'vn': '晕',  # 实际中写作 ün

    'ang': '昂',
    'eng': '鞥',
    'ing': '英',
    'ong': '翁',

    # 特殊韵母
    'er': '儿',

    # 带 i 的组合
    'ia': '呀',
    'ian': '烟',
    'iang': '央',
    'iao': '要',
    'iong': '拥',
    'iu': '优',

    # 带 u 的组合
    'ua': '蛙',
    'uai': '歪',
    'uan': '弯',
    'uang': '王',
    'ue': '约',
    'uo': '窝',
    'van': '冤',
}

# 整体认读音节
whole_readings = {
    'chi': '吃',
    'shi': '师',
    'ri': '日',
    'zi': '资',
    'ci': '佌',
    'si': '丝',
    'yi': '一',
    'wu': '屋',
    'yu': '愚',
    'ye': '椰',
    'yue': '约',
    'yuan': '渊',
    'ying': '英',
}

# 特殊字的读音
special_words = {
    'an': '安',
    'ba': '把',
    'bai': '白',
    'ban': '半',
    'bao': '包',
    'bei': '贝',
    'ben': '本',
    'bi': '比',
    'bian': '变',
    'bu': '不',
    'cai': '才',
    'can': '参',
    'cao': '草',
    'ce': '册',
    'chan': '产',
    'chang': '厂',
    'che': '车',
    'chen': '尘',
    'cheng': '成',
    'chi': '尺',
    'chong': '虫',
    'chu': '出',
    'chuan': '船',
    'chuang': '床',
    'chui': '吹',
    'chun': '春',
    'ci': '词',
    'cong': '从',
    'cun': '寸',
    'da': '大',
    'dang': '当',
    'dao': '刀',
    'de': '的',
    'deng': '灯',
    'di': '弟',
    'dian': '点',
    'ding': '丁',
    'dong': '东',
    'dou': '都',
    'duan': '短',
    'dui': '对',
    'duo': '多',
    'er': '儿',
    'fa': '发',
    'fan': '反',
    'fang': '房',
    'fei': '飞',
    'fen': '分',
    'feng': '风',
    'fu': '父',
    'gan': '赶',
    'gao': '高',
    'ge': '个',
    'geng': '更',
    'gong': '工',
    'gou': '狗',
    'gu': '故',
    'gua': '挂',
    'guan': '关',
    'guang': '广',
    'guo': '果',
    'hai': '孩',
    'hao': '好',
    'he': '和',
    'hei': '黑',
    'hong': '红',
    'hou': '后',
    'hu': '户',
    'hua': '画',
    'huan': '欢',
    'huang': '黄',
    'hui': '回',
    'huo': '火',
    'ji': '几',
    'jia': '加',
    'jian': '见',
    'jiang': '江',
    'jiao': '交',
    'jie': '姐',
    'jin': '今',
    'jing': '京',
    'jiu': '九',
    'ju': '句',
    'ka': '卡',
    'kai': '开',
    'kan': '看',
    'ke': '可',
    'kong': '空',
    'kou': '口',
    'kuai': '快',
    'lai': '来',
    'lan': '蓝',
    'lao': '老',
    'le': '了',
    'lei': '泪',
    'li': '立',
    'lian': '莲',
    'liang': '亮',
    'lin': '林',
    'liu': '六',
    'lu': '路',
    'lv': '绿',
    'ma': '妈',
    'mao': '猫',
    'me': '么',
    'mei': '没',
    'men': '门',
    'mi': '米',
    'mian': '面',
    'miao': '苗',
    'ming': '明',
    'mu': '木',
    'na': '那',
    'nai': '奶',
    'nan': '男',
    'ni': '你',
    'nian': '年',
    'niao': '鸟',
    'niu': '牛',
    'nv': '女',
    'pa': '怕',
    'pao': '跑',
    'peng': '朋',
    'pi': '皮',
    'pian': '片',
    'piao': '飘',
    'ping': '苹',
    'qi': '起',
    'qian': '前',
    'qiao': '桥',
    'qing': '青',
    'qiu': '秋',
    'qu': '去',
    'quan': '全',
    'qun': '群',
    'rang': '让',
    'ren': '人',
    'ri': '日',
    'rou': '肉',
    'ru': '入',
    'san': '三',
    'se': '色',
    'sen': '森',
    'sha': '沙',
    'shan': '山',
    'shang': '上',
    'shao': '少',
    'shen': '什',
    'sheng': '生',
    'shi': '石',
    'shou': '手',
    'shu': '叔',
    'shuang': '双',
    'shui': '水',
    'shuo': '说',
    'si': '四',
    'ta': '它',
    'tai': '台',
    'tao': '桃',
    'tian': '天',
    'tiao': '条',
    'ting': '听',
    'tong': '同',
    'tou': '头',
    'tu': '土',
    'wa': '蛙',
    'wan': '玩',
    'wang': '往',
    'wei': '为',
    'wen': '问',
    'wo': '我',
    'wu': '五',
    'xi': '西',
    'xia': '下',
    'xiang': '向',
    'xiao': '小',
    'xie': '鞋',
    'xin': '心',
    'xing': '杏',
    'xue': '学',
    'ya': '牙',
    'yan': '眼',
    'yang': '羊',
    'yao': '要',
    'ye': '爷',
    'yi': '衣',
    'yin': '音',
    'ying': '影',
    'yong': '用',
    'you': '又',
    'yu': '雨',
    'yuan': '院',
    'yue': '月',
    'yun': '云',
    'zai': '在',
    'zao': '早',
    'zhan': '站',
    'zhang': '长',
    'zhao': '找',
    'zhe': '着',
    'zhen': '真',
    'zheng': '正',
    'zhi': '只',
    'zhong': '中',
    'zhu': '竹',
    'zhuo': '桌',
    'zi': '自',
    'zou': '走',
    'zu': '足',
    'zui': '最',
    'zuo': '左',
}

# 合并所有映射
pinyin_to_hanzi = {
    **initials,
    **finals,
    **whole_readings,
    **special_words,
}

# 自定义英文单词到拼音的映射
CUSTOM_PINYIN_MAP = {
    'an': 'ān',
    'ba': 'bǎ',
    'bai': 'bái',
    'ban': 'bàn',
    'bao': 'bāo',
    'bei': 'bèi',
    'ben': 'běn',
    'bi': 'bǐ',
    'bian': 'biàn',
    'bu': 'bù',
    'cai': 'cái',
    'can': 'cān',
    'cao': 'cǎo',
    'ce': 'cè',
    'chan': 'chǎn',
    'chang': 'chǎng',
    'che': 'chē',
    'chen': 'chén',
    'cheng': 'chéng',
    'chi': 'chǐ',
    'chong': 'chóng',
    'chu': 'chū',
    'chuan': 'chuán',
    'chuang': 'chuáng',
    'chui': 'chuī',
    'chun': 'chūn',
    'ci': 'cí',
    'cong': 'cóng',
    'cun': 'cùn',
    'da': 'dà',
    'dang': 'dāng',
    'dao': 'dāo',
    'de': 'de',
    'deng': 'dēng',
    'di': 'dì',
    'dian': 'diǎn',
    'ding': 'dīng',
    'dong': 'dōng',
    'dou': 'dōu',
    'duan': 'duǎn',
    'dui': 'duì',
    'duo': 'duō',
    'er': 'ér',
    'fa': 'fā',
    'fan': 'fǎn',
    'fang': 'fáng',
    'fei': 'fēi',
    'fen': 'fēn',
    'feng': 'fēng',
    'fu': 'fù',
    'gan': 'gǎn',
    'gao': 'gāo',
    'ge': 'gè',
    'geng': 'gèng',
    'gong': 'gōng',
    'gou': 'gǒu',
    'gu': 'gù',
    'gua': 'guà',
    'guan': 'guān',
    'guang': 'guǎng',
    'guo': 'guǒ',
    'hai': 'hái',
    'hao': 'hǎo',
    'he': 'hé',
    'hei': 'hēi',
    'hong': 'hóng',
    'hou': 'hòu',
    'hu': 'hù',
    'hua': 'huà',
    'huan': 'huān',
    'huang': 'huáng',
    'hui': 'huí',
    'huo': 'huǒ',
    'ji': 'jǐ',
    'jia': 'jiā',
    'jian': 'jiàn',
    'jiang': 'jiāng',
    'jiao': 'jiāo',
    'jie': 'jiě',
    'jin': 'jīn',
    'jing': 'jīng',
    'jiu': 'jiǔ',
    'ju': 'jù',
    'ka': 'kǎ',
    'kai': 'kāi',
    'kan': 'kàn',
    'ke': 'kě',
    'kong': 'kōng',
    'kou': 'kǒu',
    'kuai': 'kuài',
    'lai': 'lái',
    'lan': 'lán',
    'lao': 'lǎo',
    'le': 'le',
    'lei': 'lèi',
    'li': 'lì',
    'lian': 'lián',
    'liang': 'liàng',
    'lin': 'lín',
    'liu': 'liù',
    'lu': 'lù',
    'lv': 'lǜ',
    'ma': 'mā',
    'mao': 'māo',
    'me': 'me',
    'mei': 'méi',
    'men': 'mén',
    'mi': 'mǐ',
    'mian': 'miàn',
    'miao': 'miáo',
    'ming': 'míng',
    'mu': 'mù',
    'na': 'nà',
    'nai': 'nǎi',
    'nan': 'nán',
    'ni': 'nǐ',
    'nian': 'nián',
    'niao': 'niǎo',
    'niu': 'niú',
    'nv': 'nǚ',
    'pa': 'pà',
    'pao': 'pǎo',
    'peng': 'péng',
    'pi': 'pí',
    'pian': 'piàn',
    'piao': 'piāo',
    'ping': 'píng',
    'qi': 'qǐ',
    'qian': 'qián',
    'qiao': 'qiáo',
    'qing': 'qīng',
    'qiu': 'qiū',
    'qu': 'qù',
    'quan': 'quán',
    'qun': 'qún',
    'rang': 'ràng',
    'ren': 'rén',
    'ri': 'rì',
    'rou': 'ròu',
    'ru': 'rù',
    'san': 'sān',
    'se': 'sè',
    'sen': 'sēn',
    'sha': 'shā',
    'shan': 'shān',
    'shang': 'shàng',
    'shao': 'shǎo',
    'shen': 'shén',
    'sheng': 'shēng',
    'shi': 'shí',
    'shou': 'shǒu',
    'shu': 'shū',
    'shuang': 'shuāng',
    'shui': 'shuǐ',
    'shuo': 'shuō',
    'si': 'sì',
    'ta': 'tā',
    'tai': 'tái',
    'tao': 'táo',
    'tian': 'tiān',
    'tiao': 'tiáo',
    'ting': 'tīng',
    'tong': 'tóng',
    'tou': 'tóu',
    'tu': 'tǔ',
    'wa': 'wā',
    'wan': 'wán',
    'wang': 'wǎng',
    'wei': 'wèi',
    'wen': 'wèn',
    'wo': 'wǒ',
    'wu': 'wǔ',
    'xi': 'xī',
    'xia': 'xià',
    'xiang': 'xiàng',
    'xiao': 'xiǎo',
    'xie': 'xié',
    'xin': 'xīn',
    'xing': 'xìng',
    'xue': 'xué',
    'ya': 'yá',
    'yan': 'yǎn',
    'yang': 'yáng',
    'yao': 'yào',
    'ye': 'yé',
    'yi': 'yī',
    'yin': 'yīn',
    'ying': 'yǐng',
    'yong': 'yòng',
    'you': 'yòu',
    'yu': 'yǔ',
    'yuan': 'yuàn',
    'yue': 'yuè',
    'yun': 'yún',
    'zai': 'zài',
    'zao': 'zǎo',
    'zhan': 'zhàn',
    'zhang': 'zhǎng',
    'zhao': 'zhǎo',
    'zhe': 'zhe',
    'zhen': 'zhēn',
    'zheng': 'zhèng',
    'zhi': 'zhǐ',
    'zhong': 'zhōng',
    'zhu': 'zhú',
    'zhuo': 'zhuō',
    'zi': 'zì',
    'zou': 'zǒu',
    'zu': 'zú',
    'zui': 'zuì',
    'zuo': 'zuǒ',
}

def replace_custom_pinyin(text):
    """
    将自定义英文单词替换为指定拼音。
    """
    for word, pinyin in CUSTOM_PINYIN_MAP.items():
        text = text.replace(word, pinyin)
    return text

def get_hanzi_from_pinyin(pinyin_str):
    """
    统一拼音查汉字逻辑：
    1. 优先查pinyin_dict.json（用户自定义/动态扩展）
    2. 查本地special_words、whole_readings等静态字典
    """
    # 1. 查json字典
    dict_path = os.path.join(os.path.dirname(__file__), 'pinyin_dict.json')
    if os.path.exists(dict_path):
        try:
            with open(dict_path, 'r', encoding='utf-8') as f:
                d = json.load(f)
            hanzi = d.get(pinyin_str.lower())
            if hanzi:
                return hanzi
        except Exception:
            pass
    # 2. 查本地静态字典
    key = pinyin_str.lower()
    if key in special_words:
        return special_words[key]
    if key in whole_readings:
        return whole_readings[key]
    # 3. 查声母、韵母
    if key in initials:
        return initials[key]
    if key in finals:
        return finals[key]
    # 4. 没找到，返回原拼音
    return pinyin_str

def is_valid_pinyin_combination(initial, final):
    """
    校验声母和韵母组合是否合法。
    :param initial: 声母（如 'x'）
    :param final: 韵母（如 'ai'）
    :return: True 合法，False 非法
    """
    # 合法拼音组合表（部分，常用，后续可扩展）
    # 这里只做基础校验，详细规则可参考《汉语拼音方案》
    # 1. 声母为空时，韵母必须能独立成音节
    # 2. 某些声母不能和某些韵母组合（如 x 不能和 ai 组合）
    # 3. zh/ch/sh/z/c/s/r/y/w 组合有特殊规则
    
    # 允许的声母
    valid_initials = set(initials.keys()) | {''}
    # 允许的韵母
    valid_finals = set(finals.keys())
    
    # 1. 检查声母和韵母是否存在
    if initial not in valid_initials or final not in valid_finals:
        return False
    
    # 2. 特殊非法组合
    # x 不能和 ai/ei/ao/ou/ia/ua 等组合
    if initial == 'x' and final in {'ai', 'ei', 'ao', 'ou', 'ia', 'ua', 'uai', 'uo'}:
        return False
    # j/q/x 不能和 u 开头的韵母（除去 ü/üe/üan/ün）
    if initial in {'j', 'q', 'x'} and final.startswith('u') and not final.startswith('ü'):
        return False
    # zh/ch/sh/r/z/c/s 不能和 iou/ia/ie/iu/ian/iong/ing/ü 等组合
    if initial in {'zh', 'ch', 'sh', 'r', 'z', 'c', 's'} and final.startswith(('i', 'ü')):
        if final not in {'i', 'in', 'ing'}:
            return False
    # y/w 只能和特定韵母组合
    if initial == 'y' and final not in {'i', 'in', 'ing', 'u', 'un', 'ue', 'uan', 'uan', 'ü', 'ün', 'ing', 'i', 'ia', 'ie', 'iao', 'ian', 'iong', 'in', 'iang', 'iong', 'u', 'ue', 'uan', 'ün'}:
        return False
    if initial == 'w' and final not in {'u', 'ua', 'uo', 'uai', 'ui', 'un', 'uan', 'uang'}:
        return False
    # 其他组合可根据需要继续补充
    return True